### ISSUE TITLE
Decide how to package language-specific fonts

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/font-shimenkan#60]
Decide whether to place all the language-specific fonts into a single big package of fonts, or release them as separate packages. This affects the documentation and licensing. For example, should they all have one OFL.txt file with all RFNs or separate ones? Which is better?

**Comment by cheuk879** [comment]
From my non-exhaustive understanding so far, & from the point of ease:
User: separate.
Development: depends on nature of expected changes.  Those affecting all/most languages are best reflected in joint package.  If only language-specific changes are anticipated, separate packages make sense.
Troubleshooting: separate.
Maintenance (documents/building): joint
Licensing: ???
The verdict may depend mainly on what changes are expected.  Perhaps before all common features are fixed/mature a joint package is more handy.  After that point, separate packages may make more sense.

**Comment by jvgaultney** [comment]
The documentation in the source tree (in the git repo) will be apply to all language variants. This will be mainly for development and testing, and will be what any future developers will use. The hope is that we can do this with markdown, but some technical issues still need to get worked out.

For users (at least for v1.0) we'd like to package the language variants separately, but have only one set of documentation. The docs would be the same for all variants, and have sections that apply to each named font.

At some later point we could do the extra programming to assemble language-specific docs that only contain info relevant to that particular variant.

**Comment by jvgaultney** [comment]
Addresses in release v1.000
